# general settings
name: ELANLNESRGANSSL_bicubic_1.1_h0.004_ks25_kc9_1000_x4
model_type: ELANSimSelfMaskLoadModel
scale: 4
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0

pre_pad: 0
tile_size: 800
tile_pad: 32
tile_process: False

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageMaskDataset
    dataroot_gt: /data0/chendu/dataset/DIV2K/DIV2K_train_multiscale_HR_subimages_512
    dataroot_lq: /data0/chendu/dataset/DIV2K/bicubicLR/x4/DIV2K_train_multiscale_HR_subimages_512
    dataroot_gt_mask: /data0/chendu/dataset/DIV2K/mask_selfsim/DIV2K_train_multiscale_HR_subimages_512/Laplacian/L/threshold-20.0/mat
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: DIV2K100
    type: PairedImageDataset
    dataroot_gt: /data0/chendu/dataset/basicsr/DIV2K100/GT/GTmod12
    dataroot_lq: /data0/chendu/dataset/basicsr/DIV2K100/bicubicLR/x4mod12
    io_backend:
      type: disk

# network structures
network_g:
  type: ELANLN
  scale: 4
  img_range: 255.
  colors: 3
  window_sizes: [4,8,16]
  m_elan: 36
  c_elan: 180
  n_share: 0
  r_expand: 2
  rgb_mean: [0.4488, 0.4371, 0.4040]

network_d:
  type: Discriminator_VGG_192
  in_chl: 3
  nf: 64

# path
path:
  pretrain_network_g: /data0/chendu/myprojects/EFDM_SIM/experiments/pretrained_models/ELANLN_retrain/ELANLN_bicubic_x4.pth
  strict_load_g: true
  param_key_g: params

#  pretrain_network_d: /data1_ssd4t/chendu/myprojects/EFDM_SIM/experiments/ESRGANSSL_bicubic_1_x4/models/net_d_200000.pth
#  param_key_d: params
#  strict_load_d: true


# training settings
train:
  gan_loss_compute: "RaGAN"
  mask_stride: 3
  ema_decay: 0.999
  simself_strategy: 'areaarea_mask_nonlocalavg_cuda_v1'
  kernel_size: 25
  scaling_factor: 0.004
  kernel_size_center: 9
  softmax_sr: True
  softmax_gt: True
  simself_dh: 64
  simself_dw: 64
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000, 250000, 275000, 287500]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-2
    reduction: mean
  selfsim_opt:
    type: L1Loss
    loss_weight: !!float 1e3
    reduction: mean
  selfsim1_opt:
    type:  KLDistanceLoss
    loss_weight: !!float 1e3
    reduction: mean
    softmax: False
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: !!float 1e0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e2
  save_img: ~

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim: # metric name
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
    lpips:
      type: calculate_lpips
      crop_border: 4
      better: lower
    dists:
      type: calculate_dists
      crop_border: 4
      better: lower

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
