# general settings
name: SPSRnoGAN_bicubic_1_x4
model_type: SPSRSimSelfMaskModel
scale: 4
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0

pre_pad: 0
tile_size: 800
tile_pad: 32
tile_process: False

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: /home/chendu/data2_hdd10t/chendu/dataset/DIV2K/DIV2K_train_multiscale_HR_subimages_512
    dataroot_lq: /home/chendu/data2_hdd10t/chendu/dataset/DIV2K/bicubicLR/x4/DIV2K_train_multiscale_HR_subimages_512

#    dataroot_gt: /home/chendu/data2_hdd10t/chendu/dataset/basicsr/BSDS100/GT/GTmod12
#    dataroot_lq: /home/chendu/data2_hdd10t/chendu/dataset/basicsr/BSDS100/bicubicLR/x4mod12

    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 30
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /home/chendu/data2_hdd10t/chendu/dataset/basicsr/Set5/GT/GTmod12
    dataroot_lq: /home/chendu/data2_hdd10t/chendu/dataset/basicsr/Set5/bicubicLR/x4mod12
    io_backend:
      type: disk

# network structures
network_g:
  type: SPSRNet
  norm_type: null
  mode: "CNA"
  nf: 64
  nb: 23
  in_nc: 3
  out_nc: 3
  gc: 32

# path
load_mode_g: original
path:
  pretrain_network_g: /data1_ssd4t/chendu/myprojects/EFDM_SIM/experiments/pretrained_models/SPSR/RRDB_PSNR_x4.pth

# training settings
train:
  Branch_pretrain: True
  Branch_init_iters: 5000
  ema_decay: 0.999

  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e0
    reduction: mean
  pixel_gradSR_opt:
    type: MSELoss
    loss_weight: !!float 1e0
    reduction: mean
  pixel_gradBranch_opt:
    type: L1Loss
    loss_weight: !!float 5e1
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True
    ssim: # metric name
      type: calculate_ssim
      crop_border: 4
      test_y_channel: True
    lpips:
      type: calculate_lpips
      crop_border: 4
      better: lower

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
